'use strict';

const PollActionTypes ={
    SUBMIT : "SUBMIT",
    GETLISTDATA : "GETLISTDATA",
    GETPOLLQUESTIONS : "GETPOLLQUESTIONS",
    NEXTQUESTION: "NEXTQUESTION",
    NEXTSUBQUESTION : "NEXTSUBQUESTION",
    PREVQUESTION : "PREVQUESTION",
    CHECKSUBQUESTION : "CHECKSUBQUESTION",
    SPINNER : "SPINNER",
    SUBMITTING: "SUBMITTING"
};
export default PollActionTypes;